name: Test Deployment
on:
  deployment_status:

permissions: read-all

jobs:
  e2eTests:
    if:
      github.repository == 'anuraghazra/github-readme-stats' &&
      github.event_name == 'deployment_status' &&
      github.event.deployment_status.state == 'success'
    name: Perform 2e2 tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Setup Node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Run end-to-end tests.
        run: npm run test:e2e
        env:
          VERCEL_PREVIEW_URL: ${{ github.event.deployment_status.target_url }}
